# Generated by Django 3.2.5 on 2021-07-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familydata',
            name='father',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familydata',
            name='first',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='familydata',
            name='index',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='familydata',
            name='last',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='familydata',
            name='mother',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familydata',
            name='second',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='familydata',
            name='third',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
