# Generated by Django 3.2.5 on 2021-08-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0002_auto_20210730_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='familydata',
            name='partner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
