# Generated by Django 3.2.5 on 2021-08-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0004_rename_mother_familydata_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familydata',
            old_name='picture',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='familydata',
            old_name='partner',
            new_name='pid',
        ),
        migrations.RemoveField(
            model_name='familydata',
            name='index',
        ),
        migrations.AlterField(
            model_name='familydata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
