# Generated by Django 3.2.5 on 2021-08-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0005_auto_20210804_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familydata',
            name='father',
        ),
        migrations.AddField(
            model_name='familydata',
            name='partner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='familydata',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
